# Use the official Node image as the base image
FROM node:16 as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application to the working directory
COPY . .

# Build the Angular app
RUN npm run build --prod

# Use a smaller, production-ready image
FROM nginx:alpine

# Copy the built Angular app to the default Nginx public directory
COPY --from=builder /app/dist/* /usr/share/nginx/html/

# Expose port 80
EXPOSE 4200

# Command to run the Nginx server
CMD ["nginx", "-g", "daemon off;"]
